const data = [
  {
    QNo: 1,
    Question:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    option_a: "A",
    option_b: "B",
    option_c: "C",
    option_d: "D",
    option_e: "E",
    option_f: "F",
    option_a_image: "azarul",
    option_b_image: "azarul",
    option_c_image: "azarul",
    option_d_image: "azarul",
    option_e_image: "azarul",
    option_f_image: "azarul",
    question_image: "azarul",
  },
  {
    QNo: 2,
    Question:
      "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.",
    option_a: "A",
    option_b: "B",
    option_c: "C",
    option_d: "D",
    option_e: "E",
    option_f: "F",
    option_a_image: "azarul",
    option_b_image: "azarul",
    option_c_image: "azarul",
    option_d_image: "azarul",
    option_e_image: "azarul",
    option_f_image: "azarul",
    question_image: "azarul",
  },
];
